---
- name: Deploy Flask Web Application
  hosts: prod
  become: yes
  tasks:
    - name: Clone the Git repository
      git:
        repo: https://github.com/iampsrv/aws-flask.git
        dest: /home/ubuntu/application

    - name: Install Python dependencies
      pip:
        requirements: /home/ubuntu/application/req.txt
        
    - name: Start the Flask application
      shell: nohup python3 /home/ubuntu/application/app.py  > /dev/null 2>&1 &