---
- name: Clone the Git repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dest }}"
  tags: 
    - clone_repo

- name: Install Python dependencies
  pip:
    requirements: "{{ requirements_file }}"
  tags: 
    - install_dependencies

- name: Start the Flask application
  shell: nohup python3 "{{ app_path }}" > /dev/null 2>&1 &
  tags: 
    - start_app
